# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
python:
  - "2.7"
install:
  - sudo pip install knowledge-repo
  - ./travis-tool.sh install_deps

